/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as ProfileImport } from './routes/profile'
import { Route as DashboardImport } from './routes/dashboard'
import { Route as GoalsIndexImport } from './routes/goals/index'
import { Route as GoalsCreateImport } from './routes/goals/create'
import { Route as GoalsGoalIdImport } from './routes/goals/$goalId'
import { Route as GoalsGoalIdEditImport } from './routes/goals_/$goalId/edit'

// Create Virtual Routes

const RegisterLazyImport = createFileRoute('/register')()
const LoginLazyImport = createFileRoute('/login')()
const IndexLazyImport = createFileRoute('/')()

// Create/Update Routes

const RegisterLazyRoute = RegisterLazyImport.update({
  path: '/register',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/register.lazy').then((d) => d.Route))

const LoginLazyRoute = LoginLazyImport.update({
  path: '/login',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/login.lazy').then((d) => d.Route))

const ProfileRoute = ProfileImport.update({
  path: '/profile',
  getParentRoute: () => rootRoute,
} as any)

const DashboardRoute = DashboardImport.update({
  path: '/dashboard',
  getParentRoute: () => rootRoute,
} as any)

const IndexLazyRoute = IndexLazyImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

const GoalsIndexRoute = GoalsIndexImport.update({
  path: '/goals/',
  getParentRoute: () => rootRoute,
} as any)

const GoalsCreateRoute = GoalsCreateImport.update({
  path: '/goals/create',
  getParentRoute: () => rootRoute,
} as any)

const GoalsGoalIdRoute = GoalsGoalIdImport.update({
  path: '/goals/$goalId',
  getParentRoute: () => rootRoute,
} as any)

const GoalsGoalIdEditRoute = GoalsGoalIdEditImport.update({
  path: '/goals/$goalId/edit',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/dashboard': {
      preLoaderRoute: typeof DashboardImport
      parentRoute: typeof rootRoute
    }
    '/profile': {
      preLoaderRoute: typeof ProfileImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      preLoaderRoute: typeof LoginLazyImport
      parentRoute: typeof rootRoute
    }
    '/register': {
      preLoaderRoute: typeof RegisterLazyImport
      parentRoute: typeof rootRoute
    }
    '/goals/$goalId': {
      preLoaderRoute: typeof GoalsGoalIdImport
      parentRoute: typeof rootRoute
    }
    '/goals/create': {
      preLoaderRoute: typeof GoalsCreateImport
      parentRoute: typeof rootRoute
    }
    '/goals/': {
      preLoaderRoute: typeof GoalsIndexImport
      parentRoute: typeof rootRoute
    }
    '/goals/$goalId/edit': {
      preLoaderRoute: typeof GoalsGoalIdEditImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexLazyRoute,
  DashboardRoute,
  ProfileRoute,
  LoginLazyRoute,
  RegisterLazyRoute,
  GoalsGoalIdRoute,
  GoalsCreateRoute,
  GoalsIndexRoute,
  GoalsGoalIdEditRoute,
])

/* prettier-ignore-end */
