/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as PublicImport } from './routes/_public'
import { Route as AuthImport } from './routes/_auth'
import { Route as IndexImport } from './routes/index'
import { Route as PublicIndexImport } from './routes/_public/index'
import { Route as PublicRegisterImport } from './routes/_public/register'
import { Route as PublicLoginImport } from './routes/_public/login'
import { Route as AuthDashboardRouteImport } from './routes/_auth/dashboard/route'
import { Route as AuthProfileIndexImport } from './routes/_auth/profile/index'
import { Route as AuthProfileEditImport } from './routes/_auth/profile/edit'
import { Route as AuthDashboardGroupsRouteImport } from './routes/_auth/dashboard/groups/route'
import { Route as AuthDashboardGoalsRouteImport } from './routes/_auth/dashboard/goals/route'
import { Route as AuthDashboardGroupsCreateImport } from './routes/_auth/dashboard/groups/create'
import { Route as AuthDashboardGoalsCreateImport } from './routes/_auth/dashboard/goals/create'
import { Route as AuthDashboardGroupsGroupIdIndexImport } from './routes/_auth/dashboard/groups/$groupId/index'
import { Route as AuthDashboardGoalsGoalIdIndexImport } from './routes/_auth/dashboard/goals/$goalId/index'
import { Route as AuthDashboardGroupsGroupIdEditImport } from './routes/_auth/dashboard/groups/$groupId/edit'
import { Route as AuthDashboardGoalsGoalIdEditImport } from './routes/_auth/dashboard/goals/$goalId/edit'

// Create/Update Routes

const PublicRoute = PublicImport.update({
  id: '/_public',
  getParentRoute: () => rootRoute,
} as any)

const AuthRoute = AuthImport.update({
  id: '/_auth',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const PublicIndexRoute = PublicIndexImport.update({
  path: '/',
  getParentRoute: () => PublicRoute,
} as any)

const PublicRegisterRoute = PublicRegisterImport.update({
  path: '/register',
  getParentRoute: () => PublicRoute,
} as any)

const PublicLoginRoute = PublicLoginImport.update({
  path: '/login',
  getParentRoute: () => PublicRoute,
} as any)

const AuthDashboardRouteRoute = AuthDashboardRouteImport.update({
  path: '/dashboard',
  getParentRoute: () => AuthRoute,
} as any)

const AuthProfileIndexRoute = AuthProfileIndexImport.update({
  path: '/profile/',
  getParentRoute: () => AuthRoute,
} as any)

const AuthProfileEditRoute = AuthProfileEditImport.update({
  path: '/profile/edit',
  getParentRoute: () => AuthRoute,
} as any)

const AuthDashboardGroupsRouteRoute = AuthDashboardGroupsRouteImport.update({
  path: '/groups',
  getParentRoute: () => AuthDashboardRouteRoute,
} as any)

const AuthDashboardGoalsRouteRoute = AuthDashboardGoalsRouteImport.update({
  path: '/goals',
  getParentRoute: () => AuthDashboardRouteRoute,
} as any)

const AuthDashboardGroupsCreateRoute = AuthDashboardGroupsCreateImport.update({
  path: '/create',
  getParentRoute: () => AuthDashboardGroupsRouteRoute,
} as any)

const AuthDashboardGoalsCreateRoute = AuthDashboardGoalsCreateImport.update({
  path: '/create',
  getParentRoute: () => AuthDashboardGoalsRouteRoute,
} as any)

const AuthDashboardGroupsGroupIdIndexRoute =
  AuthDashboardGroupsGroupIdIndexImport.update({
    path: '/$groupId/',
    getParentRoute: () => AuthDashboardGroupsRouteRoute,
  } as any)

const AuthDashboardGoalsGoalIdIndexRoute =
  AuthDashboardGoalsGoalIdIndexImport.update({
    path: '/$goalId/',
    getParentRoute: () => AuthDashboardGoalsRouteRoute,
  } as any)

const AuthDashboardGroupsGroupIdEditRoute =
  AuthDashboardGroupsGroupIdEditImport.update({
    path: '/$groupId/edit',
    getParentRoute: () => AuthDashboardGroupsRouteRoute,
  } as any)

const AuthDashboardGoalsGoalIdEditRoute =
  AuthDashboardGoalsGoalIdEditImport.update({
    path: '/$goalId/edit',
    getParentRoute: () => AuthDashboardGoalsRouteRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/_auth': {
      preLoaderRoute: typeof AuthImport
      parentRoute: typeof rootRoute
    }
    '/_public': {
      preLoaderRoute: typeof PublicImport
      parentRoute: typeof rootRoute
    }
    '/_auth/dashboard': {
      preLoaderRoute: typeof AuthDashboardRouteImport
      parentRoute: typeof AuthImport
    }
    '/_public/login': {
      preLoaderRoute: typeof PublicLoginImport
      parentRoute: typeof PublicImport
    }
    '/_public/register': {
      preLoaderRoute: typeof PublicRegisterImport
      parentRoute: typeof PublicImport
    }
    '/_public/': {
      preLoaderRoute: typeof PublicIndexImport
      parentRoute: typeof PublicImport
    }
    '/_auth/dashboard/goals': {
      preLoaderRoute: typeof AuthDashboardGoalsRouteImport
      parentRoute: typeof AuthDashboardRouteImport
    }
    '/_auth/dashboard/groups': {
      preLoaderRoute: typeof AuthDashboardGroupsRouteImport
      parentRoute: typeof AuthDashboardRouteImport
    }
    '/_auth/profile/edit': {
      preLoaderRoute: typeof AuthProfileEditImport
      parentRoute: typeof AuthImport
    }
    '/_auth/profile/': {
      preLoaderRoute: typeof AuthProfileIndexImport
      parentRoute: typeof AuthImport
    }
    '/_auth/dashboard/goals/create': {
      preLoaderRoute: typeof AuthDashboardGoalsCreateImport
      parentRoute: typeof AuthDashboardGoalsRouteImport
    }
    '/_auth/dashboard/groups/create': {
      preLoaderRoute: typeof AuthDashboardGroupsCreateImport
      parentRoute: typeof AuthDashboardGroupsRouteImport
    }
    '/_auth/dashboard/goals/$goalId/edit': {
      preLoaderRoute: typeof AuthDashboardGoalsGoalIdEditImport
      parentRoute: typeof AuthDashboardGoalsRouteImport
    }
    '/_auth/dashboard/groups/$groupId/edit': {
      preLoaderRoute: typeof AuthDashboardGroupsGroupIdEditImport
      parentRoute: typeof AuthDashboardGroupsRouteImport
    }
    '/_auth/dashboard/goals/$goalId/': {
      preLoaderRoute: typeof AuthDashboardGoalsGoalIdIndexImport
      parentRoute: typeof AuthDashboardGoalsRouteImport
    }
    '/_auth/dashboard/groups/$groupId/': {
      preLoaderRoute: typeof AuthDashboardGroupsGroupIdIndexImport
      parentRoute: typeof AuthDashboardGroupsRouteImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexRoute,
  AuthRoute.addChildren([
    AuthDashboardRouteRoute.addChildren([
      AuthDashboardGoalsRouteRoute.addChildren([
        AuthDashboardGoalsCreateRoute,
        AuthDashboardGoalsGoalIdEditRoute,
        AuthDashboardGoalsGoalIdIndexRoute,
      ]),
      AuthDashboardGroupsRouteRoute.addChildren([
        AuthDashboardGroupsCreateRoute,
        AuthDashboardGroupsGroupIdEditRoute,
        AuthDashboardGroupsGroupIdIndexRoute,
      ]),
    ]),
    AuthProfileEditRoute,
    AuthProfileIndexRoute,
  ]),
  PublicRoute.addChildren([
    PublicLoginRoute,
    PublicRegisterRoute,
    PublicIndexRoute,
  ]),
])

/* prettier-ignore-end */
